//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        private static Entities _context;
        public Entities()
            : base("name=Entities")
        {
        }
    
        public static Entities GetContext()
        {
            if (_context == null) _context = new Entities();
            return _context;

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Goroda> Goroda { get; set; }
        public virtual DbSet<Napravleniya> Napravleniya { get; set; }
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Polsovateli> Polsovateli { get; set; }
        public virtual DbSet<Roli> Roli { get; set; }
        public virtual DbSet<Sobitiya> Sobitiya { get; set; }
        public virtual DbSet<Strani> Strani { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
