//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sobitiya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sobitiya()
        {
            this.Polsovateli = new HashSet<Polsovateli>();
        }
    
        public int IdSobitiya { get; set; }
        public string Nazvanie { get; set; }
        public System.DateTime Data { get; set; }
        public int Days { get; set; }
        public Nullable<int> IdGoroda { get; set; }
    
        public virtual Goroda Goroda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polsovateli> Polsovateli { get; set; }
    }
}
